apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout-canary
spec:
  replicas: 3
  analysis:
    successfulRunHistoryLimit: 10
    unsuccessfulRunHistoryLimit: 10
  selector:
    matchLabels:
      app: guestbook
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReadySeconds: 30
  revisionHistoryLimit: 3

  paused: true

  progressDeadlineSeconds: 600

  progressDeadlineAbort: false

  restartAt: "2020-03-30T21:19:35Z"

  rollbackWindow:
    revisions: 3

  strategy:

    # Blue-green update strategy
    blueGreen:

      activeService: active-service

      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: guestbook-svc.default.svc.cluster.local

      # Post-promotion analysis run which performs analysis after the service
      # cutover. +optional
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: guestbook-svc.default.svc.cluster.local

      previewService: preview-service

      previewReplicaCount: 1

      autoPromotionEnabled: false

      autoPromotionSeconds: 30


      scaleDownDelaySeconds: 30

      scaleDownDelayRevisionLimit: 2

      abortScaleDownDelaySeconds: 30

      antiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: {}
        preferredDuringSchedulingIgnoredDuringExecution:
          weight: 1 # Between 1 - 100

    

status:
  pauseConditions:
  - reason: StepPause
    startTime: 2019-10-00T1234
  - reason: BlueGreenPause
    startTime: 2019-10-00T1234
  - reason: AnalysisRunInconclusive
    startTime: 2019-10-00T1234 
